name: style_test
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/Mehmetyaz/style/tree/main/packages/style_test/
repository: https://github.com/Mehmetyaz/style

environment:
  sdk: '>=2.14.0 <3.0.0'


dependencies:
  test: ^1.19.3
  meta: ^1.7.0
  style_dart: ^1.0.2
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.1

