name: style_test
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: '>=2.14.9 <3.0.0'


dependencies:
  test: ^1.19.3
  meta: ^1.7.0
  json_schema2: ^2.0.0+3
  style_dart:
    path: ../style
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.1

