
builders:
  style_serialize:
    import: "package:style_object_builder/builder.dart"
    builder_factories: [ "styleSerializable" ]
    build_extensions: { ".dart": [ "style_serializable.g.part" ] }
    auto_apply: dependents
    build_to: cache
    applies_builders: [ "source_gen|combining_builder" ]