name: style
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.0 <3.0.0'


dependencies:
  mongo_dart_query: ^1.0.2
  stack_trace: ^1.10.0
#  style_interface:
#    path: ../style_interface
  analyzer: ^2.3.0

dev_dependencies:
#  style_documentor:
#    path: ../style_documentor
  build_runner: ^2.1.2
  effective_dart: ^1.3.2
  test: ^1.17.12


