name: style_dart
description: A starting point for Dart libraries or applications.
version: 1.0.1
homepage: https://github.com/Mehmetyaz/style/tree/main/packages/style/

publish_to: none

environment:
  sdk: '>=2.14.9 <3.0.0'


dependencies:
  queue: ^3.1.0
  stack_trace: ^1.10.0
  style_cron_job: ^1.0.0
  meta: ^1.7.0


dev_dependencies:
  cryptography: ^2.0.2
  effective_dart: ^1.3.2
  test: ^1.19.1
  style_test:
    path: ../style_test


