name: style
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.15.0-118.0.dev <3.0.0'


dependencies:
  style_interface:
    path: ../style_interface

dev_dependencies:
  effective_dart: ^1.3.2
  test: ^1.17.12
