name: style_dart
description: A starting point for Dart libraries or applications.
version: 1.0.1
homepage: https://github.com/Mehmetyaz/style/tree/main/packages/style/
repository: https://github.com/Mehmetyaz/style


publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'





dependencies:
  args: ^2.3.0
  queue: ^3.1.0+1
  json_schema2: ^2.0.0+3
  style_cron_job:
    path: ../style_cron_job
  meta: ^1.7.0


dev_dependencies:
  cryptography: ^2.0.4
  effective_dart: ^1.3.2
  test: ^1.19.3
  style_test:
    path: ../style_test


