name: style
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.15.0-118.0.dev <3.0.0'


dependencies:
  queue: ^3.1.0
  stack_trace: ^1.10.0
#  style_interface:
#    path: ../style_interface
  analyzer: ^2.4.0

dev_dependencies:
  style_cron_job:
    path: ../style_cron_job
  http: ^0.13.3
#  style_documentor:
#    path: ../style_documentor
  build_runner: ^2.1.4
  effective_dart: ^1.3.2
  test: ^1.17.12


