name: simple
description: A simple style data access server.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  style_dart:
    path: ../../../style

dev_dependencies:
  build_web_compilers: ^3.2.1
  build_runner: ^2.1.4
  effective_dart: ^1.3.2
